### ISSUE TITLE
Can't install App::DuckPAN

### ISSUE THREAD

**Issue by barreyra** [duckduckgo/p5-app-duckpan#250]
When I first tried using `cpanm App::DuckPAN`, it complained about not being able to find WWW::DuckDuckGo. After using the suggested installer here, it complains about not being able to find DDG::Goodie, DDG::Publisher, DDG::Spice, DDG::Request, DDG::Test::Language, DDG::Test::Location.

    $ uname -a
    Darwin brbarrey-mac03.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by moollaza** [comment]
@barreyra sorry about that, I'm already in the process of fixing this!

**Comment by barreyra** [comment]
I'm glad it wasn't something dumb I did! :)

**Comment by moollaza** [comment]
@barreyra have you run `curl http://duckpan.org/install.pl | perl` that should solve your problems...

**Comment by barreyra** [comment]
```
 ____             _    ____             _     ____
|  _ \ _   _  ___| | _|  _ \ _   _  ___| | __/ ___| ___
| | | | | | |/ __| |/ / | | | | | |/ __| |/ / |  _ / _ \
| |_| | |_| | (__|   <| |_| | |_| | (__|   <| |_| | (_) |
|____/ \__,_|\___|_|\_\____/ \__,_|\___|_|\_\\____|\___/
=========================================================

Found running local::lib...

Installing App::DuckPAN...

[WARNING] This may take a while :-)

Module::Finder is up to date. (v0.1.5)
Module::Extract::VERSION is up to date. (1.01)
namespace::autoclean is up to date. (0.24)
Moose is up to date. (2.1404)
Crypt::SSLeay is up to date. (0.72)
Starman is up to date. (0.4011)
--> Working on App::DuckPAN
Fetching http://www.cpan.org/authors/id/M/MO/MOOLLAZA/App-DuckPAN-0.180.tar.gz ... OK
Configuring App-DuckPAN-0.180 ... OK
==> Found dependencies: DDG::Test::Language, DDG::Goodie, DDG::Spice, DDG::Publisher, DDG::Test::Location, DDG::Request
! Finding DDG::Test::Language on cpanmetadb failed.
! Finding DDG::Test::Language (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution DDG::Test::Language
! Finding DDG::Goodie on cpanmetadb failed.
! Finding DDG::Goodie (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution DDG::Goodie
! Finding DDG::Spice on cpanmetadb failed.
! Finding DDG::Spice (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution DDG::Spice
! Finding DDG::Publisher on cpanmetadb failed.
! Finding DDG::Publisher (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution DDG::Publisher
! Finding DDG::Test::Location on cpanmetadb failed.
! Finding DDG::Test::Location (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution DDG::Test::Location
! Finding DDG::Request on cpanmetadb failed.
! Finding DDG::Request (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution DDG::Request
! Installing the dependencies failed: Module 'DDG::Goodie' is not installed, Module 'DDG::Test::Language' is not installed, Module 'DDG::Request' is not installed, Module 'DDG::Test::Location' is not installed, Module 'DDG::Publisher' is not installed, Module 'DDG::Spice' is not installed
! Bailing out the installation for App-DuckPAN-0.180.

[ERROR] Failure on install of modules!

This could have several reasons, for first you can just restart this installer,
cause it could be a pure download problem. If this isnt the case, please read
the build.log mentioned on the errors and see if you can fix the problem
yourself. Otherwise, please report the problem via email to use at
open@duckduckgo.com with the build.log attached. If there is no build.log
mentioned, just attach the output you see.
```

**Comment by moollaza** [comment]
Alright I've released a fix, please try again!

**Comment by moollaza** [comment]
@barreyra also, I'm in the process of updating the README, but we now have Node.js as a dependency for running DuckPAN.

More details here:
https://github.com/duckduckgo/p5-app-duckpan/blob/moollaza/dependency-update/README.md#installing-duckpan-locally

**Comment by barreyra** [comment]
@moollaza, do I need to bypass the installation script and clone directly from github? The installation script is still fetching http://www.cpan.org/authors/id/M/MO/MOOLLAZA/App-DuckPAN-0.180.tar.gz

**Comment by barreyra** [comment]
I tried a clean install again today, and I still get this issue:

```
! Installing the dependencies failed: Module 'WWW::DuckDuckGo' is not installed
! Bailing out the installation for DDG-0.133.
7 distributions installed
```

I am able to get further by doing a `cpanm -M http://duckpan.org WWW::DuckDuckGo`, but the installer is still not working out-of-the-box.

**Comment by moollaza** [comment]
@barreyra sorry, I see the problem and will fix soon

**Comment by moollaza** [comment]
@barreyra WWW::DuckDuckGo has been added back to CPAN so everything should be OK.
